#[target.x86_64-unknown-linux-gnu]
#linker = "x86_64-unknown-linux-gnu-gcc"
#[target.all]
#rustflags = ["-C", "target-cpu=native"]

#[build]
#[bench]
#rustflags = ["-C", "target-cpu=native",]

#[target.x86_64-pc-windows-gnu]
#[target.x86_64-pc-windows-msvc]
#rustflags = [
#    "-C",
#    "target-cpu=native",
#]
